### PR TITLE
Fix some typo's

### PR DESCRIPTION
**Pull request by mvanthoor**
As the title says: this PR fixes some typo's.

### CODE REVIEW

**Comment by algerbrex** [comment]
Thanks, I'll merge this in shortly.

**Review by BernhardHofmann — APPROVED** [review]
Nice to see people helping make this repo even better. <3

**Comment by algerbrex** [comment]
Thanks, @BernhardHofmann, definitely. I'm glad people are taking some interest. I'll be approving all of these pull requests on the next release of Blunder.

**Comment by algerbrex** [comment]
Thanks @mvanthoor, I also share a similar sentiment. Of course nothing wrong if an author chooses to work alone and only then share their engine, but it's nice and helpful to see things done from scratch and people work their engine up from mid-to-low 1000s up with 3000+. I also feel it's much more rewarding to heavily document things starting out so you can see how far you've come.

And excellent to hear regarding XBoard support. I look forward to seeing you finish your tuner and release the next version of Rustic! :)

**Pull request merged**
